server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy API calls to taskapi
    location ~* ^/(tasks|tags|locations|counts|pipelines|filters) {
        proxy_pass         http://api:8081;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # SPA fallback — all other paths serve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
