apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskmgt-data
  namespace: taskmgt
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
